/* Leitura de fotos somente no IndexedDB deste aparelho. CSP impede conexões. */
(function(){
'use strict';
const $=id=>document.getElementById(id),C=RelatorioCore;let context,ds,ss,photos=[],images=[],urls=[];
function status(t){$('status').textContent=t;}
function save(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function prefix(){return String(context.projection.codigo).replace(/[^a-z0-9_-]/gi,'_');}
function zip(files){return FotosPptx.zip(files.map(f=>f.dados?f:{nome:f.nome,dados:new TextEncoder().encode(f.text)}));}
function canvasBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Falha ao preparar imagem.')),'image/jpeg',.88));}
async function imageFromCanvas(canvas,caption){const blob=await canvasBlob(canvas);return {blob,bytes:new Uint8Array(await blob.arrayBuffer()),width:canvas.width,height:canvas.height,caption};}
async function photoImage(p){const u=URL.createObjectURL(p.blob);try{const im=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Uma foto local não pôde ser lida.'));im.src=u;});const c=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(im.naturalWidth,im.naturalHeight));c.width=Math.round(im.naturalWidth*scale);c.height=Math.round(im.naturalHeight*scale);const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(im,0,0,c.width,c.height);const t=context.projection.tratamentos.find(t=>t.id===p.treatment);return imageFromCanvas(c,(t?t.id+' · '+t.produto:p.treatment)+' · R'+p.rep+' · Parcela '+(p.plot||'não identificada')+' · '+p.date+' · Avaliação '+(p.assessment||'não vinculada'));}finally{URL.revokeObjectURL(u);}}
async function charts(){const groups=new Map(),out=[];context.projection.resultados.forEach(r=>{const key=JSON.stringify([r.avaliacao,r.variavel,r.tipo,r.unidade,r.sentido]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);});
 for(const rows of groups.values()){for(let start=0;start<rows.length;start+=10){const rs=rows.slice(start,start+10),c=document.createElement('canvas');c.width=1200;c.height=130+rs.length*62;const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.fillStyle='#172923';g.font='bold 25px sans-serif';g.fillText(rs[0].variavel+' · '+rs[0].data+' · '+rs[0].avaliacao,30,40,1130);const min=Math.min(0,...rows.map(r=>r.media)),max=Math.max(0,...rows.map(r=>r.media)),span=max-min||1,x=v=>260+(v-min)/span*690;
 g.strokeStyle='#aaa';g.beginPath();g.moveTo(x(0),65);g.lineTo(x(0),c.height-45);g.stroke();rs.forEach((r,i)=>{const y=75+i*62;g.fillStyle='#172923';g.font='20px sans-serif';g.fillText(r.tratamento,30,y+22,210);g.fillStyle='#207151';g.fillRect(Math.min(x(0),x(r.media)),y,Math.max(1,Math.abs(x(r.media)-x(0))),30);g.fillStyle='#172923';g.fillText(String(Math.round(r.media*1000)/1000)+' '+(r.unidade||'')+' (n='+r.n+')',970,y+22,210);});g.font='17px sans-serif';g.fillText('Médias descritivas; sem teste de médias. Ausências não são zero.',30,c.height-15);out.push(await imageFromCanvas(c,rs[0].variavel+' por tratamento · '+rs[0].data+' · '+rs[0].avaliacao+(rows.length>10?' · parte '+(1+start/10):'')+'. Consulte a tabela de tratamentos para nomes e doses.'));}}
 return out;
}
async function prepare(){const buttons=document.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);$('downloads').hidden=true;status('Preparando relatório e figuras no aparelho…');try{
 urls.forEach(URL.revokeObjectURL);urls=[];images=await charts();if($('include-photos').checked){for(const p of photos)images.push(await photoImage(p));}
 $('report').innerHTML='<h1>Relatório do estudo '+C.esc(context.projection.codigo)+'</h1>'+C.html(ss)+'<h2>Figuras e fotos</h2>'+images.map(im=>{const u=URL.createObjectURL(im.blob);urls.push(u);return '<figure><img src="'+u+'" alt="'+C.esc(im.caption)+'"><figcaption>'+C.esc(im.caption)+'</figcaption></figure>';}).join('');
 if(!$('include-photos').checked)$('report').insertAdjacentHTML('beforeend','<p>Fotos locais não incluídas nesta exportação.</p>');
 $('downloads').hidden=false;status('Relatório pronto. Confira a prévia antes de baixar.');
 }catch(e){status('Não foi possível concluir: '+e.message);}finally{buttons.forEach(b=>b.disabled=false);}}
window.addEventListener('message',async ev=>{if(context||ev.origin!==location.origin||ev.source!==parent||!ev.data||ev.data.type!=='agracta:report-context')return;const c=ev.data.context;if(!c||!c.owner||!c.projection||!c.study)return;context=c;ds=C.data(c);ss=C.sections(c,ds);$('actions').hidden=false;status('Dados recebidos. Prepare a prévia ou exporte para R.');try{photos=await FotosStore.create(indexedDB,JSON.stringify([c.owner,c.projection.qid,c.projection.sid])).list();$('photo-status').textContent=photos.length+' foto(s) neste aparelho. A inclusão é opcional.';}catch(e){$('photo-status').textContent='Fotos locais indisponíveis: '+e.message;$('include-photos').disabled=true;}});
$('prepare').onclick=prepare;$('include-photos').onchange=()=>{$('downloads').hidden=true;status('Prepare novamente a prévia para aplicar a escolha de fotos.');};
$('r').onclick=()=>{try{const c={...context};delete c.owner;save(new Blob([zip(C.rFiles(c,ds))],{type:'application/zip'}),prefix()+'_R.zip');}catch(e){status(e.message);}};
$('docx').onclick=()=>{try{save(new Blob([FotosPptx.zip(RelatorioDocx.parts(context,ss,images))],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),prefix()+'_relatorio.docx');}catch(e){status(e.message);}};
$('md').onclick=()=>{try{const files=[{nome:'relatorio.md',text:C.markdown(context,ss,images)},...images.map((im,i)=>({nome:'imagens/figura-'+(i+1)+'.jpg',dados:im.bytes}))];save(new Blob([zip(files)],{type:'application/zip'}),prefix()+'_markdown.zip');}catch(e){status(e.message);}};
$('pdf').onclick=()=>window.print();
})();
