'use strict';
const assert=require('node:assert/strict'),C=require('./vendor/conhecimento-core'),F=require('./vendor/fontes-core'),P=require('./vendor/portal-core');
assert.equal(C.numero(''),null);assert.equal(C.numero('  '),null);assert.equal(C.numero('3abc'),null);assert.equal(C.numero(false),null);assert.equal(C.numero('1,5'),1.5);
assert.deepEqual(C.resumo(['',null,0,'2,0','4']),{n:3,media:2,dp:2,min:0,max:4});assert.equal(C.resumo([2]).dp,null);
const a={eventos:[{id:'a',ts:1,tipo:'campo',chave:'projeto',valor:'Estudo integrado'},{id:'p',ts:3,tipo:'preco',chave:'c1',valor:2,unidade:'mL'}]},b={eventos:[{id:'b',ts:2,tipo:'campo',chave:'loteBiologico',valor:'Isolado-1'}]};
assert.deepEqual(C.merge(a,b),C.merge(b,a));assert.deepEqual(C.merge(C.merge(a,b),a),C.merge(a,b));
const cs=[{id:'c1',quantidade:5,unidade:'mL',tratamento:'T1',aplicacao:'P1'},{id:'c2',quantidade:8,unidade:'g',tratamento:'T2'}];
assert.equal(C.custo(cs,a).total,10);assert.equal(C.custo(cs,a).semPreco,1);assert.equal(C.custo(cs,a).completo,false);
assert.equal(C.custo([{id:'c1',quantidade:5,unidade:'g'}],a).total,0);
const desp={id:'d',ts:4,tipo:'custo',quantidade:2,valorUnitario:50,categoria:'Equipe'};
assert.equal(C.custo(cs,C.merge(a,{eventos:[desp]})).total,110);
assert.equal(C.custo(cs,C.merge(a,{eventos:[desp,{id:'s',ts:5,tipo:'estorno',alvo:'d'}]})).total,10);
assert.deepEqual(C.agruparCustos(C.custo(cs,a),'tratamento'),[{nome:'T1',total:10,semPreco:0},{nome:'T2',total:0,semPreco:1}]);
assert.equal(C.soloNoInicio([{data:'2026-09-01'},{data:'2026-08-01'}],'2026-08-12').data,'2026-08-01');assert.equal(C.soloNoInicio([{data:'2026-09-01'}],'2026-08-12'),null);
const s={key:C.chave('Q1','S1'),codigo:'S1',alvo:'Alvo A',cultura:'Soja',ambiente:'campo',local:'Local A',tratamentos:[{id:'T1',produto:'Cego 01',identidades:[{key:'item:i1',nome:'Cego 01'}],dose:'1 L/ha'}],resultados:[{avaliacao:'A1',tratamento:'T1',variavel:'Dano',n:4,media:10,dp:2,data:'2026-09-01'}],integracoes:a,aplicacoes:[{id:'P1',data:'2026-08-01',clima:{temp:20,fonte:'Estação',histor:true,instante:false,mac:'SEGREDO'}}],audit:'INTERNO',custos:{total:900},coordenadas:[1,2]};
const s2=JSON.parse(JSON.stringify(s));s2.key=C.chave('Q2','S1');s2.codigo='S2';s2.resultados[0].media=90;s2.cultura='Milho';
const ac=C.construir([s,s2]);assert.equal(ac.produtos[0].estudos.length,2);assert.equal(C.selecionar(ac,{cultura:'soja'}).length,1);
assert.deepEqual(C.resultados([s,s2],{}).map(r=>r.media),[10,90]);
const pub=C.relatorioCliente(s),json=JSON.stringify(pub);assert(!/INTERNO|SEGREDO|custos|coordenadas|integracoes|item:i1/.test(json));assert.equal(pub.ambienteEventos[0].clima.histor,true);
assert.equal(pub.ambienteEventos[0].clima.instante,false);assert.equal(pub.resultados[0].produto,'Cego 01');
assert.equal(P.id(C.chave('A/B','C')),encodeURIComponent('["A/B","C"]'));
assert.throws(()=>P.validar({nome:'X',emails:'a@b.com',estudos:[]}));assert.throws(()=>P.validar({nome:'X',emails:'a/b@c.com',estudos:['s']}));
assert.deepEqual(P.validar({nome:'X',emails:'A@b.com, a@b.com',estudos:['s','s'],auto:true}),{nome:'X',emails:['a@b.com'],estudos:['s'],auto:true});
const prop={schema:1,itemId:'i',fonte:'Base licenciada de teste',url:'https://example.com/dados',licenca:'Autorização de teste',consultadoEm:'2026-09-01',propriedades:[{nome:'Propriedade fictícia',valor:1,unidade:'mg/L',condicoes:'20 °C',referencia:'Registro sintético'}]};
assert.equal(F.validar(prop,'i').propriedades[0].valor,1);assert.throws(()=>F.validar(prop,'outro'));assert.throws(()=>F.validar({...prop,url:'javascript:alert(1)'},'i'));assert.throws(()=>F.validar({...prop,licenca:''},'i'));assert.throws(()=>F.validar({...prop,propriedades:[{...prop.propriedades[0],valor:'1'}]},'i'));
console.log('Conhecimento: valores ausentes, resumos, merge, custos, contexto, isolamento e importações OK.');
