'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),C=require('./vendor/relatorio-core'),D=require('./vendor/relatorio-docx'),Z=require('./vendor/fotos-pptx');
(async()=>{
const context={schema:'agracta-relatorio-1',generated:'2026-09-12T14:00:00Z',projection:{qid:'Q01',sid:'S01',codigo:'EXEMPLO 001',local:'Iracemápolis',quadra:'Q01',cultura:'Soja',alvo:'Doença avaliada',inicio:'2026-08-01',tratamentos:[{id:'T1',produto:'Testemunha',dose:'',metodo:'CO₂'},{id:'T2',produto:'SC 193',dose:'1,5 L/ha',metodo:'CO₂'}],resultados:[{avaliacao:'001',data:'2026-08-15',variavel:'Severidade',unidade:'%',tratamento:'T1',n:2,media:12.5,dp:3.5,controle:null},{avaliacao:'001',data:'2026-08-15',variavel:'Severidade',unidade:'%',tratamento:'T2',n:1,media:0,dp:null,controle:100}]},study:{id:'S01',codigo:'EXEMPLO 001',descricao:'Avaliar os resultados dos tratamentos nas condições registradas.',numRepeticoes:2,desenho:'dbc',randomizado:true,randomizacao:{ordem:[{tratId:'T2',rep:1,parcela:103},{tratId:'T1',rep:1,parcela:101}]},avaliacoes:[{id:'001',data:'2026-08-15',variaveis:['Severidade'],tipos:{Severidade:'pct'},notas:{T1R1:{Severidade:'10,0'},T1R2:{Severidade:15},T2R1:{Severidade:0},T2R2:{Severidade:''}},bruto:{T1R1:{Severidade:{sub:[10,20]}}},avaliadores:{A:{nome:'Avaliador A',notas:{T1R1:{Severidade:9}}},B:{nome:'Avaliador B',notas:{T1R1:{Severidade:11}}}}}],audit:[{action:'Cadastro',nome:'Responsável',iso:'2026-08-01'}]},context:{quadra:{solo:{classe:'Classe registrada'}},custos:{total:null,semPreco:1}},analysis:{jobs:[{jobKey:'pending',modo:'estatistica',variavel:'Severidade'}],results:{}},forensics:[]};
const before=JSON.stringify(context),d=C.data(context),ss=C.sections(context,d);
assert.equal(d.observacoes.length,4);assert.equal(d.observacoes[0].valor,10);assert.equal(d.observacoes[2].valor,0);assert.equal(d.observacoes[3].valor,null);assert.equal(d.observacoes[3].estado,'ausente');assert.equal(d.observacoes[2].parcela,103);assert.equal(d.avaliadores.length,8);assert.equal(d.subamostras.length,2);assert.equal(d.subamostras[0].tratamento,'T1');assert.equal(d.subamostras[0].campo,'/sub/0');assert.equal(C.data({...context,study:{...context.study,randomizado:false}}).parcelas[0].parcela,'');
assert.equal(C.data({...context,study:{...context.study,numRepeticoes:1}}).observacoes.length,2);
assert.equal(C.number('não avaliado'),null);assert.equal(C.number(false),null);
const rf=C.rFiles(context,d);assert(rf.find(f=>f.nome==='importar.R').text.includes('colClasses="character"'));assert(rf.find(f=>f.nome==='observacoes.csv').text.includes('"ausente"'));assert(rf.find(f=>f.nome==='registros_completos.json').text.includes('sub'));
assert.equal(C.csv([{a:'um,"dois"\ntrês'}],['a']),'"a"\r\n"um,""dois""\ntrês"\r\n');
assert(C.html(ss).includes('Pendente'));assert(C.markdown(context,ss).includes('Anexo completo'));
assert(!C.html([{title:'<img>',headers:['h'],rows:[['<script>']],text:''}]).includes('<script>'));
const parts=D.parts(context,ss);assert(parts.find(f=>f.nome==='word/document.xml'));assert(parts.find(f=>f.nome==='word/styles.xml'));assert.equal(new Uint8Array(await Z.zip(parts).arrayBuffer())[0],80);assert.equal(JSON.stringify(context),before);
for(const f of ['relatorio-local.js','vendor/relatorio-core.js','vendor/relatorio-docx.js'])assert(!/\bfetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon/.test(fs.readFileSync(f,'utf8')),f);
assert.match(fs.readFileSync('relatorio-local.html','utf8'),/connect-src 'none'/);
assert.match(fs.readFileSync('sw.js','utf8'),/galeria-local\|relatorio-local/);
if(process.env.RELATORIO_QA){fs.mkdirSync(process.env.RELATORIO_QA,{recursive:true});fs.writeFileSync(process.env.RELATORIO_QA+'/exemplo.docx',new Uint8Array(await Z.zip(parts).arrayBuffer()));fs.writeFileSync(process.env.RELATORIO_QA+'/context.json',JSON.stringify(context));fs.writeFileSync(process.env.RELATORIO_QA+'/exemplo_R.zip',new Uint8Array(await Z.zip(rf.map(f=>({nome:f.nome,dados:new TextEncoder().encode(f.text)}))).arrayBuffer()));}
console.log('Relatório e R: zero, ausências, decimal, randomização, avaliadores, subamostras, uma repetição, CSV, DOCX, sem mutação e sem rede OK.');

})().catch(e=>{console.error(e);process.exit(1);});
