'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const P=require('../vendor/protocolo-avaliacao-core'),A=require('../vendor/avaliacao-core');
const st={numRepeticoes:2,tratamentos:[{id:'T1',testemunha:true,papelControle:'sem_alvo'},{id:'T2',testemunha:true,papelControle:'sem_intervencao'},{id:'T3',papelControle:'positivo'}],avaliacoes:[]};
const p={variaveis:[{nome:'folha',tipo:'pct',cfg:{calculoControle:'auto',referencia:'T2'}},{nome:'isca',tipo:'pct',cfg:{calculoControle:'nenhum',naTratamentos:['T1','T2']}}]};
const av=Object.assign({id:'a',data:'2026-09-29',notas:{T1R1:{folha:0},T1R2:{folha:0},T2R1:{folha:90},T2R2:{folha:90},T3R1:{folha:9,isca:0},T3R2:{folha:9,isca:50}}},P.snapshot(p,{data:'2026-09-29'}));st.avaliacoes=[av];
assert.equal(A.avaliacao(st,av).complete,true,'NA resolves pending without zeros');
assert.equal(av.notas.T1R1.isca,undefined,'no fabricated value');
delete av.notas.T3R1.isca;assert.equal(A.avaliacao(st,av).complete,false,'empty applicable stays pending');av.notas.T3R1.isca=0;
const before=JSON.stringify(st);P.preparar(st,p,['a']);assert.equal(JSON.stringify(st),before,'preflight is read only');
const bad=structuredClone(p);bad.variaveis[0].cfg.naTratamentos=['T3'];assert.throws(()=>P.preparar(st,bad,['a']),/existe leitura/);
const dates=structuredClone(p);dates.variaveis[0].datas=['2026-09-30'];assert.throws(()=>P.preparar(st,dates,['a']),/existe leitura/);
av.carimbo={rubrica:'x'};assert.throws(()=>P.preparar(st,p,['a']),/assinada/);delete av.carimbo;
const dup=structuredClone(p);dup.variaveis.push(dup.variaveis[0]);assert.throws(()=>P.preparar(st,dup,[]),/repetido/);
const source=fs.readFileSync('app.js','utf8');function fun(name){let a=source.indexOf('function '+name+'('),i=source.indexOf('{',a),depth=1,j=i+1;for(;depth;j++){if(source[j]==='{')depth++;if(source[j]==='}')depth--;}return source.slice(a,j);}
const c={AvaliacaoCore:A,window:{},AV_TIPOS:{pct:1,escala:1},_avRowsForStudy:A.linhas};vm.createContext(c);
['_numBR','_avTipo','_avCfg','_avDerivar','studyTestemunha','_avNota','_avMeans','_avSentido','_pctCtrl','_avEficacia'].forEach(n=>vm.runInContext(fun(n),c));
st.testemunha='T2';assert.equal(c.studyTestemunha(st),'T2');assert.equal(c._avEficacia(st,av,'folha','T3',0,9,{metodo:'abbott'}),90,'explicit T2 overrides wrong global reference');assert.equal(c._avEficacia(st,av,'folha','T1',90,0,{metodo:'abbott'}),null,'no-target control is not efficacy');
assert.equal(c._avDerivar({tipo:'escala',escalaModo:'nota',escalaMin:0,escalaMax:4},{sub:[1,3]}),'2');assert.equal(c._avDerivar({tipo:'escala',escalaMin:0,escalaMax:4},{sub:[1,3]}),'50','legacy index preserved');
console.log('Protocolo: duas testemunhas, positivo, NA, zero, assinatura, referências e escalas OK');
